services:
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile
    ports:
      - "8000:80"
    environment:
      APP_ENV: ${APP_ENV:-dev}
      APP_SECRET: ${APP_SECRET:-change-me}
      DATABASE_URL: mysql://app:app@database:3306/ecommerce?serverVersion=8&charset=utf8mb4
      MAILER_DSN: ${MAILER_DSN:-null://null}
    depends_on:
      - database
    volumes:
      - .:/var/www/symfony

  database:
    image: mysql:8.2
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE:-ecommerce}
      MYSQL_USER: ${MYSQL_USER:-app}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-app}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-root}
    volumes:
      - database_data:/var/lib/mysql

  adminer:
    image: adminer
    restart: always
    ports:
        - "8026:8080"

volumes:
  database_data:
